### ISSUE TITLE
报告怎么没有看到？

### ISSUE THREAD

**Issue by evilbinary** [im0qianqian/Reversi-based-RL#2]

**Comment by im0qianqian** [comment]
啥东西？麻烦描述清楚一点

**Comment by evilbinary** [comment]
开题报告（2019.02.25 - 2019.03.10）
 中期检查（2019.04.20 - 2019.04.30）
 作品验收（2019.05.16 - 2019.05.19）
 毕业论文（2019.05.20 - 2019.05.29）
 毕业答辩（2019.05.30 - 2019.06.06）

**Comment by im0qianqian** [comment]
README 里只是一个自己的计划，所涉及到的东西并没有全部上传。

**Comment by evilbinary** [comment]
这样啊
